### ISSUE TITLE
How can this problem be solved

### ISSUE THREAD

**Issue by mawom** [cmdruid/buff#1]
ReferenceError: crypto is not defined
    at file:///D:/RenGui/Documents/Backups/tapscript-master/node_modules/@cmdcode/buff-utils/src/utils.ts:6:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
How can this problem be solved

**Comment by cmdruid** [comment]
Hello. Can you try updating your nodejs to v19 or above? That usually will fix the issue.
