### ISSUE TITLE
Error trying to require the package

### ISSUE THREAD

**Issue by dannybabbev** [cmdruid/buff#2]
I did `npm install @cmdcode/buff-utils`

I get this error when trying to require and use the package:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/@cmdcode/buff-utils/package.json
```

I am requiring it like:
```
const { Buff } = require('@cmdcode/buff-utils');
```

```
node --version
v20.10.0
```

**Comment by cmdruid** [comment]
`buff-utils` is the name for an older version of the package.

Try using the newer version which should have an `exports` defined that makes nodejs happy: `npm install @cmdcode/buff`

Let me know if that helps.
